### ISSUE TITLE
 Integration has stopped working :(

### ISSUE THREAD

**Issue by kozlik07** [n4ts/ha-notione#3]
ha log errors:
is it possible to correct it

Logger: homeassistant.components.device_tracker
Source: custom_components/notione/device_tracker.py:124
Integration: Śledzenie urządzeń (documentation, issues)
First occurred: 13:33:51 (1 occurrences)
Last logged: 13:33:51

Error setting up platform legacy notione
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 255, in async_setup_legacy
    setup = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/notione/device_tracker.py", line 43, in setup_scanner
    NotiOneTracker(hass, config, see)
  File "/config/custom_components/notione/device_tracker.py", line 68, in __init__
    update_interval(None)
  File "/config/custom_components/notione/device_tracker.py", line 63, in update_interval
    self._update_info()
  File "/config/custom_components/notione/device_tracker.py", line 124, in _update_info
    if entity_picture[0:4] != 'http':
TypeError: 'NoneType' object is not subscriptable

**Comment by n4ts** [comment]
fixed [bc0357b](https://github.com/n4ts/ha-notione/commit/bc0357b08f02bff393a96dc12ea8e7979e550ffa)
