### ISSUE TITLE
Integration fails at startup

### ISSUE THREAD

**Issue by ssuukk** [n4ts/ha-notione#5]
The log:

```2024-02-05 14:55:07.941 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy notione
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 311, in async_setup_legacy
    setup = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/notione/device_tracker.py", line 43, in setup_scanner
    NotiOneTracker(hass, config, see)
  File "/config/custom_components/notione/device_tracker.py", line 68, in __init__
    update_interval(None)
  File "/config/custom_components/notione/device_tracker.py", line 63, in update_interval
    self._update_info()
  File "/config/custom_components/notione/device_tracker.py", line 102, in _update_info
    lat = dev['lastPosition']['latitude']
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable```

**Comment by n4ts** [comment]
@ssuukk  Can you send me the content of the endpoint response: https://api.notinote.me/secured/internal/devicelist ? You can obfuscate sensitive data if you want.

**Comment by ssuukk** [comment]
Sure. Any way to do it from the browser dev console, or should I just try to open this url from your code?
